apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    tier: website
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: website
  template:
    metadata:
      labels:
        tier: website
    spec:
      containers:
      - name: web
        image: jaibw/frozenyogurtshop
---
apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  selector:
    tier: website
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
