apiVersion: apps/v1
kind: Deployment
metadata:
  name: yourname
  labels:
    tier: yourname
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: yourname
  template:
    metadata:
      labels:
        tier: yourname
    spec:
      containers:
      - name: web
        image: nginx
