apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-yourname
  labels:
    tier: backend-yourname
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: backend-yourname
  template:
    metadata:
      labels:
        tier: backend-yourname
    spec:
      containers:
      - name: web
        image: stenote/nginx-hostname
---
apiVersion: v1
kind: Service
metadata:
  name: backend-yourname
spec:
  selector:
    tier: backend-yourname
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-yourname
  labels:
    tier: frontend-yourname
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend-yourname
  template:
    metadata:
      labels:
        tier: frontend-yourname
    spec:
      containers:
      - name: web
        image: stenote/nginx-hostname
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-yourname
spec:
  selector:
    tier: frontend-yourname
  type: NodePort 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
