apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-website
spec:
  capacity:
    storage: 11Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.31.7.185
    path: "/data/website"
  mountOptions:
    - nfsvers=4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-demo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: nfs-website    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-web-yourname
spec:
  replicas: 3
  selector:
    matchLabels:
      role: nfs-web-yourname
  template:
    metadata:
      labels:
        role: nfs-web-yourname
    spec:
      containers:
      - name: web
        image: nginx
        ports:
          - name: web
            containerPort: 80
        volumeMounts:
            - name: nfs
              mountPath: "/usr/share/nginx/html"
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs-demo
---
apiVersion: v1
kind: Service
metadata:
  name: web-yourname
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    role: nfs-web-yourname
